# Generated by Django 5.2.10 on 2026-01-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_comment_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reply",
                to="comments.user",
            ),
            preserve_default=False,
        ),
    ]
