# Generated by Django 5.2.10 on 2026-01-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_alter_reply_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="votes",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reply",
            name="votes",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
